INSERT INTO goods(id,commodity_id,name,manufacturer,cost,quantity,sell_out,characteristics,description,category,addedby)
VALUES (1,'b5e5eca5-ff25-4734-94e0-3138ba91ba28','laptop HP Envy 13-d000ur (N7H79EA)','HP',1102.84,5,'No',
        'Screen 13.3 "IPS (1920x1080) Full HD, matte / Intel Core i5-6200U (2.3 - 2.8 GHz) / RAM 8 GB / SSD 128GB / Intel HD Graphics 520 / OD without / LAN / Wi-Fi / Bluetooth / web camera / Windows 10 Home 64bit / 1.36 kg / silver / Details: http://rozetka.com.ua/hp_n7h79ea/p6429274/',
        'Compact and stylish HP Envy 13 notebook with a record slim. This stylish and sleek notebook has a high performance full-fledged PC.  Perfect execution  Due processors 6th generation Intel Core i5, SSD capacity of 128 GB and a wide range of different slots this notebook combines the convenience of a thin body and a high performance full-fledged PC. Incredibly long battery operation. Size does not matter. This lightweight and stylish notebook has an incredibly powerful battery that provides up to 9 hours of intensive mode. Attractive design. This thin and light notebook is easy to transport and will be an excellent assistant during business trips. In addition, it is able to supplement your business image. Bang & Olufsen sound with two speakers Bang & Olufsen sound with two speakers - is a guarantee of incredibly realistic and rich sound. Perfect audio playback. Solid State drive High-speed hard disk will not disappoint even the most demanding users. Rate high speed download applications through a fast and efficient SSDs. Processors Intel`s sixth-generationsixth-generation Intel Core processors operate more quietly and quickly. They sold a lot of features that are not available on previous models.Backlit KeyboardUse the device even in areas with low light or during night air travel. Backlit keyboard allows you to type in any light.Amazing quality graphicsIntel adapter provides superior quality graphics for games, leisure and other purposes.HP USB Sleep and ChargeHP USB Sleep and Charge technology allows you to charge devices via the laptop even when it is off, in sleep mode or hibernation mode. Thus, the device you want to be always at hand and in full readiness to work.Bi-directional microphonePlease rate the quality of communication during a video chat, which was made possible thanks to the bi-directional microphone and noise reduction program.Webcam HP TrueVision HDRate incredibly clear picture, so you do not miss a single detail - even in low light. Enjoy live communication thanks to HP TrueVision high-definition webcam.Security Tool HP SimplePassRate incredibly easy access to accounts on the Internet: to be logged in just one move of the finger, with your personal data remains protected. HP SimplePass allows you to save passwords, which greatly simplifies access to your favorite sites and services.Details: http://rozetka.com.ua/hp_n7h79ea/p6429274/',
        'laptops','420ad08b-0043-48b0-a9f6-b952d9ae5272');
INSERT INTO goods(id,commodity_id,name,manufacturer,cost,quantity,sell_out,characteristics,description,category,addedby)
VALUES (2,'7ae10df7-f786-4168-853e-f8670ab10e71','laptop HP Omen 15-5250ur (N7H99EA) Black ','HP',2096.44,5,'No',
          'Screen 15.6 "IPS (1920x1080) Full HD Multitouch, matt, touch / Intel Core i7-4720HQ (2.6 GHz) / RAM 8 GB / SSD 256GB / nVidia GeForce GTX 960M, 4GB / OD without / LAN / Wi-Fi / Bluetooth / web camera / Windows 10 Home 64bit / 2.12 kg / black / Details: http://rozetka.com.ua/hp_omen_n7h99ea/p8054448/',
          'Power high-performance notebook HP Omen is not inferior to a desktop PC and allow you to take a call anytime and anywhere. Defeat opponents stunning graphics, lightning-fast processing speed, realistic sound and customizable features. Performance of a new level Defeat opponents arsenal worthy of your skills. Graphics card nVidia GeForce GTX 960m and high performance Intel Core i7 processor 4th generation fully support the most demanding games. Wherever you are - keep playing optimizing battery technology allows you to play for hours, consuming less energy and achieving better performance. This slim and light notebook combines high mobility and power of a desktop computer. Graphics card nVidia GeForce GTX Ideal for home games and on the road. Rate Gorgeous game graphics, faster processing of multimedia and Battery Boost technology from nVidia. You can even automatically capture interesting moments of the games and share them with friends. Attractive design Play your way: thin and light notebook, you can always take with you. This gaming notebook thickness of 19.9 mm and a weight of 2.12 kg differs incredible performance and comprehensive capabilities. HP Solid State Drive High-speed solid-state drive will not disappoint even the most demanding users. Solid-state drive capacity of 256 GB of games speed up boot time by 2-3 times. Best keyboard for gaming Special game keys and customizable profiles for each game provides additional control and help you not to miss a single movement. Backlit Keyboard Keep playing even in rooms with dim lighting or when the night air travel. Backlit keyboard allows you to type in any light. HP TrueVision Webcam A clear image that you do not miss a single detail, even in low light. Enjoy live communication thanks to HP TrueVision webcam. HP USB Boost HP USB Boost technology allows you to charge devices via the laptop even when it is off, in sleep mode or hibernation mode. Since the device you want to be always at hand and in full readiness to work. BeatsAudio Thanks to technology and BeatsAudio pair speakers HP Omen laptop is able to reproduce the highest quality and rich sound on the PC. Many connectors The perfect device for gaming enthusiasts. For user convenience, all the connectors on the rear panel. Forget cables - focus on the game. Details: http://rozetka.com.ua/hp_omen_n7h99ea/p8054448/',
          'laptops','420ad08b-0043-48b0-a9f6-b952d9ae5272');
INSERT INTO goods(id,commodity_id,name,manufacturer,cost,quantity,sell_out,characteristics,description,category,addedby)
VALUES (3,'450599e9-690c-4463-a311-d8482a71a0fa','smartphone Blackberry Z30 Black','Blackberry',342.49,0,'No',
          'Details: http://rozetka.com.ua/blackberry_z30_black/p1271710/',
          'We offer you a new way to use your smartphone. This where the smartphone should move your thoughts, help solve your problem quickly, smoothly, and quietly. Discover the BlackBerry Z30, designed for your forward movement. Stay at the peak of the event - keep everything you need in one place. You go in the BlackBerry Hub from any screen on your phone with a single gesture, to easily check your messages and notification. The new BlackBerry touch keyboard simplifies typing. It learns your style input and offers the most typical for you in a particular phrase word, allowing you to enter text more accurately, quickly and with minimal effort. Over time, the keyboard remembers - and correct - your inaccuracies in the character set, reducing typing errors to a minimum. Select and change elements of the image to create the desired photo. At the time shift mode of capture of a few milliseconds to your photos in a few milliseconds after - so you can go back using the scale and open the eyes of a friend, and then go ahead to choose a smile each other, then combine all to create the perfect shot . BlaskBerry World now provides access to diverse content. Download applications, games, books, magazines and more. Recommendations on the BlackBerry World will help you to better navigate the new arrivals. Keeper of their ideas, interests and projects in one convenient place Take your Z30 with an office - BlackBerry Balance will help to separate personal and business information Save time when scheduling and management tasks - details to clarify your BlackBerry Calendar Explore the new and larger share your discoveries with your friends - pages load at lightning speed, displaying a surprisingly clear, page placement in social networks just as ever Your information is secure, the BlackBerry security that you know and trust, even better BlaskBerry Tag with NFC technology simplifies the data exchange process Send a message, an appointment, update status on Facebook - with the help of the voice control Crop, adjust and enhance your photos, and share them with friends in just one click Elegant, crisp, delicate - think of life in all its vivid detail Details: http://rozetka.com.ua/blackberry_z30_black/p1271710/',
          'smartphones','f01498b6-11cd-4a3f-aed8-b8c51336a265');
INSERT INTO goods(id,commodity_id,name,manufacturer,cost,quantity,sell_out,characteristics,description,category,addedby)
VALUES (4,'701ac149-3f08-40b7-af5e-ac60b9f9445e','smartphone Sony Xperia Z5 Dual Premium Black','Sony',886.24,5,'Yes',
          'Screen (5.5 ", IPS, 3840x2160) / Qualcomm Snapdragon 810 MSM8994 (Quad 2 GHz + Quad 1.5 GHz) / main camera: 23 megapixel front camera 5 MP / RAM 3 GB / 32 GB internal memory + microSD / SDHC (up to 200 GB) / 3G / LTE / GPS / support 2 SIM-cards (Nano-SIM) / Android 5.1 (Lollipop) / 3430 mAh / Details: http://rozetka.com.ua/sony_xperia_premium_z5_dual_black/p4954151/',
          'Imagine a smartphone with a bright, clear display, which utilizes the best television technology Sony. This smartphone - Xperia Z5 Dual Premium. Its 5.5-inch display has a resolution of 4K Ultra HD, which is four times greater than Full HD. Hperiya Z5 Dual Premium makes a huge breakthrough in video technology: every inch of the display is divided into 806 pixels, which makes the picture extremely sharp. pixel density is 10 times higher than on a TV Full HD TV, and twice as high as in most smartphones. Xperia Z5 Dual Premium increases the resolution of your photos and video to 4K, preserving every detail and making them more expressive. Hperiya Z5 Dual Premium is not shy of the public - on the contrary, he likes to be in sight. The smartphone is the Xperia true corporate identity: it is available with a chrome, black and gold trim and the rear panel has a mirror surface. With the Xperia Z5 Dual Premium, you can shoot video in 4K resolution, which is four times higher than Full HD. On the quality of the image will take care of a variety of video technology the Sony, including the SteadyShot, is responsible for ensuring that the picture is not shaking. Capture frames from a video resolution of 8 megapixels. Often, the most striking moments come not in the photo and on video. From their videos shot in 4K format, you can choose a valuable resource and make high-quality 8-megapixel photos. The power button on the Xperia Z5 Dual Premium integrated fingerprint reader. The button itself is located on the side of the smartphone, so you can quickly unlock the screen in one motion. Such a powerful 4K-smartphone relies fitting battery: Sony outfitted its battery that can run for up to two days without recharging. All this time, you can watch movies, listen to music and chat with friends. When designing Xperia Z5 Dual Premium, Sony Xperia remained faithful to the philosophy and paid attention to every last detail, to all of it was perfect. Under the hood of the Xperia Z5 Dual Premium Qualcomm Snapdragon 810 64-bit, eight cores, allowing the smartphone to operate at lightning speed. With support for High-Resolution Audio each note will sound perfectly clean, and digital noise reduction technology removes all extraneous sounds. Details: http://rozetka.com.ua/sony_xperia_premium_z5_dual_black/p4954151/',
          'smartphones','d0c122ff-2d0e-4113-a3c2-ce3bc4e6fd78');
INSERT INTO users(id,username,password,email,firstname,lastname,role,user_id)
VALUES (1, 'admin', 'password', 'amdin@email.com', 'admin', 'admin', 0, 'bdfb129d-d30c-4bc9-a456-8973539f2ec8');
INSERT INTO users(id,username,password,email,firstname,lastname,role,user_id)
VALUES (2, 'Hewlett Packard', 'password', 'hp@email.com', 'Hewlett-Packard', 'Hewlett-Packard', 1, '420ad08b-0043-48b0-a9f6-b952d9ae5272');
INSERT INTO users(id,username,password,email,firstname,lastname,role,user_id)
VALUES (3, 'Bob Dylan', 'password', 'example@email.com', 'Bob', 'Dylan', 2, '420ad08b-0043-48b0-a9f6-b952d9ae5272');
INSERT INTO users(id,username,password,email,firstname,lastname,role,user_id)
VALUES (5, 'Blackberry', 'password', 'blackberry@email.com', 'Blackberry', 'Blackberry', 1, 'f01498b6-11cd-4a3f-aed8-b8c51336a265');
INSERT INTO users(id,username,password,email,firstname,lastname,role,user_id)
VALUES (4, 'Sony', 'password', 'sony@email.com', 'Sony', 'Sony', 1, 'd0c122ff-2d0e-4113-a3c2-ce3bc4e6fd78');
